name: Build and upload artifact
on:
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'Name of the artifact'     
        required: true
        type: string
        default: test
  workflow_call:
    inputs:
     artifact-name:
       description: 'Name of the artifact'
       required: true
       type: string
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    name: Build and upload artifact
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read node and npm versions from package.json
      uses: skjnldsv/read-package-engines-version-actions@v1
      id: package-engines-versions
    - uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.package-engines-versions.outputs.nodeVersion }}'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      name: Cache node_modules
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --non-interactive --frozen-lockfile
    - name: Build
      run: yarn run build
    - name: Upload build
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ github.workspace }}/build
        retention-days: 7