name: Delete artifacts
on:
  workflow_call:
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Script
        uses: actions/github-script@v6.1.0
        with:
          script: node scripts/delete-artifacts.js
          debug: true