name: Delete artifacts
on:
  workflow_dispatch:
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read node and npm versions from package.json
        uses: skjnldsv/read-package-engines-version-actions@v1
        id: package-engines-versions
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.package-engines-versions.outputs.nodeVersion }}'
      - name: ls -la
        run: ls -la
      # - name: GitHub Script
      #   uses: actions/github-script@v6.1.0
      #   with:
      #     script: |
      #       const script = require('./scripts/delete-artifacts.js');
      #       console.log(script({ context }))
      #     debug: true